name: ticket_booking_app
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  fluentui_icons: ^1.0.0
  get:
  gap: ^2.0.0
  flutter_screenutil: ^5.5.4
  barcode_widget: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0
  




flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
